repository_type: pipeline
lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-corephylo_logo_light.png
  - docs/images/nf-core-corephylo_logo_light.png
  - docs/images/nf-core-corephylo_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  - .github/workflows/branch.yml
  - .github/workflows/ci.yml
  - .github/workflows/linting_comment.yml
  - .github/workflows/linting.yml
  nextflow_config:
  - manifest.name
  - manifest.homePage
  readme:
  - nextflow_badge
