name: MASKRC
description: Masks recombinant regions in an alignment based on ClonalFrameML or Gubbins output
keywords:
  - alignment
  - recombinant
  - ClonalFrameML
tools:
  - maskrc-svg:
      description: Masks recombinant regions in an alignment based on ClonalFrameML or Gubbins output
      homepage: https://github.com/kwongj/maskrc-svg
      documentation: https://github.com/kwongj/maskrc-svg
      tool_dev_url: https://github.com/kwongj/maskrc-svg
      licence: ["GPL v3"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - cfml:
      type: file
      description: |
        ClonalFrameML output files
  - aln:
      type: file
      description: |
        Multiple sequence alignment

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - aln:
      type: file
      description: Multiple sequence alignment with recombinant regions masked
      pattern: "*.aln"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@rpetit3"
  - "@oschwengers"
